// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// clip-lines.cpp
cpp11::writable::list clip_lines_impl(cpp11::doubles x, cpp11::doubles y, cpp11::integers id, double p_mid_x, double p_mid_y, double width, double height, double theta, double asp);
extern "C" SEXP _isoband_clip_lines_impl(SEXP x, SEXP y, SEXP id, SEXP p_mid_x, SEXP p_mid_y, SEXP width, SEXP height, SEXP theta, SEXP asp) {
  BEGIN_CPP11
    return cpp11::as_sexp(clip_lines_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(id), cpp11::as_cpp<cpp11::decay_t<double>>(p_mid_x), cpp11::as_cpp<cpp11::decay_t<double>>(p_mid_y), cpp11::as_cpp<cpp11::decay_t<double>>(width), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(theta), cpp11::as_cpp<cpp11::decay_t<double>>(asp)));
  END_CPP11
}
// isoband.cpp
cpp11::writable::list isobands_impl(cpp11::doubles x, cpp11::doubles y, cpp11::doubles_matrix<> z, cpp11::doubles value_low, cpp11::doubles value_high);
extern "C" SEXP _isoband_isobands_impl(SEXP x, SEXP y, SEXP z, SEXP value_low, SEXP value_high) {
  BEGIN_CPP11
    return cpp11::as_sexp(isobands_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(z), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value_low), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value_high)));
  END_CPP11
}
// isoband.cpp
cpp11::writable::list isolines_impl(cpp11::doubles x, cpp11::doubles y, cpp11::doubles_matrix<> z, cpp11::doubles value);
extern "C" SEXP _isoband_isolines_impl(SEXP x, SEXP y, SEXP z, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(isolines_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(z), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value)));
  END_CPP11
}
// separate-polygons.cpp
cpp11::writable::list separate_polygons(cpp11::doubles x, cpp11::doubles y, cpp11::integers id);
extern "C" SEXP _isoband_separate_polygons(SEXP x, SEXP y, SEXP id) {
  BEGIN_CPP11
    return cpp11::as_sexp(separate_polygons(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(id)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_isoband_clip_lines_impl",   (DL_FUNC) &_isoband_clip_lines_impl,   9},
    {"_isoband_isobands_impl",     (DL_FUNC) &_isoband_isobands_impl,     5},
    {"_isoband_isolines_impl",     (DL_FUNC) &_isoband_isolines_impl,     4},
    {"_isoband_separate_polygons", (DL_FUNC) &_isoband_separate_polygons, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_isoband(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
