# Generated by cpp11: do not edit by hand

clip_lines_impl <- function(x, y, id, p_mid_x, p_mid_y, width, height, theta, asp) {
  .Call(`_isoband_clip_lines_impl`, x, y, id, p_mid_x, p_mid_y, width, height, theta, asp)
}

isobands_impl <- function(x, y, z, value_low, value_high) {
  .Call(`_isoband_isobands_impl`, x, y, z, value_low, value_high)
}

isolines_impl <- function(x, y, z, value) {
  .Call(`_isoband_isolines_impl`, x, y, z, value)
}

separate_polygons <- function(x, y, id) {
  .Call(`_isoband_separate_polygons`, x, y, id)
}
