# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clip_lines_impl <- function(x, y, id, p_mid_x, p_mid_y, width, height, theta) {
    .Call(`_isoband_clip_lines_impl`, x, y, id, p_mid_x, p_mid_y, width, height, theta)
}

isobands_impl <- function(x, y, z, value_low, value_high) {
    .Call(`_isoband_isobands_impl`, x, y, z, value_low, value_high)
}

isolines_impl <- function(x, y, z, value) {
    .Call(`_isoband_isolines_impl`, x, y, z, value)
}

separate_polygons <- function(x, y, id) {
    .Call(`_isoband_separate_polygons`, x, y, id)
}

